### ISSUE TITLE
Uncaught exception 'RuntimeException' with message 'SplFileInfo::getSize(): stat

### ISSUE THREAD

**Issue by enricocanino** [outlandishideas/sync#2]
I have just downloaded your sync package and after shortly installed it.

I think that it is a great php class and i hope to use it.

Unfortunately I get this error message:

Fatal error: Uncaught exception 'RuntimeException' with message 'SplFileInfo::getSize(): stat failed for //etc/alternatives/convert.1.gz' in /htdocs/public/www/httpsync/AbstractSync.php:41 Stack trace: #0 /htdocs/public/www/httpsync/AbstractSync.php(41): SplFileInfo->getSize() #1 /htdocs/public/www/httpsync/Client.php(25): Outlandish\Sync\AbstractSync->getFileList('/') #2 /htdocs/public/www/httpsync/sync.php(9): Outlandish\Sync\Client->run('http://www.gest...') #3 {main} thrown in /htdocs/public/www/httpsync/AbstractSync.php on line 41

I havo no ideas about...

Thanks in advance.

**Comment by tamlyn** [comment]
> //etc/alternatives/convert.1.gz

That double slash looks odd. Can you post the code you're using to run `sync`?

**Comment by enricocanino** [comment]
<?php

// script di sincronizzazione, lato client che riceve la sincronizzazione
 include 'AbstractSync.php';
 include 'Client.php';
 const SECRET = 'mysecretcode'; //make this long and complicated
 const PATH = '/prova_client'; // directory di destinazione dei file prelevati dal server
 $client = new \Outlandish\Sync\Client(SECRET, PATH);
 $client->run('http://www.mysecrethost.it/httpsync/remote.php'); // si connette con il server e sincronizza
?>

**Comment by enricocanino** [comment]
I apologize but problem was error in absolute path.

Php class works fine.

Thanks a lot.
